format = """
\\[$username@$hostname\\]\
$directory\
$shlvl\
$kubernetes\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$ruby\
$rust\
$swift\
$terraform\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$env_var\
$crystal\
$cmd_duration\
$time\
$status\
$custom\
$line_break\
$jobs\
$battery\
$character"""

[username]
format = "[$user]($style)"

[hostname]
format = "[$hostname]($style)"

[directory]
truncation_length = 0
truncate_to_repo = false

[time]
disabled = false
format = '[\($time\)]($style)'
time_format = '%FT%T'

[status]
disabled = false

[git_branch]
format = "[git:\\[$branch\\]]($style)"

[aws]
disabled = true

[gcloud]
disabled = true
